services:
  next-server:
    image: mrobroie/blog-app:build-040d4d9d9864b068d19268b42f751aad28e54f7a
    deploy:
      replicas: 5
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    ports:
      - '3000:3000'
    networks:
      - blog-app-net
networks:
  blog-app-net: null
