services:
  next-server:
    image: mrobroie/blog-app:build-c83aaa5ddc30cff7f5979544e4db5cce27c8bb6c
    deploy:
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    ports:
      - '3000:3000'
    networks:
      - blog-app-net
networks:
  blog-app-net: null
