services:
  next-server:
    image: nextjs/blog-app:build-d8d40b601283bd5f50caab3665c05c902232600d
    deploy:
      replicas: 5
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    ports:
      - '3000:3000'
    networks:
      - blog-app-net
  blog-server:
    image: mrobroie/blog-app:build-670c94a69e059f80d745339c43a49aa2ebbecac3
networks:
  blog-app-net: null
