name: First Action

# When to run the action
on:
  pull_request:
    branches: ["main"]

# Jobs to run
# Lint Job For ESlint
jobs:
  lint:
    runs-on: ubuntu-latest
    
    # Matrix Strategy to run the job on multiple versions of Node.js
    strategy:
      matrix:
        node-version: ["18.x", "20.x", "22.x"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  # Build Job For Build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build
# Every Job Creates A new VM and runs the commands
# So if you want to run multiple commands in a single VM
# You can create a single job and run multiple commands in it
# Like this
# test_and_lint_and_build:
#   runs-on: ubuntu-latest

#   steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: "18"

#     - name: Install dependencies
#       run: npm install

#     - name: Run Tests
#       run: npm test

#     - name: Run ESLint
#       run: npm run lint

#     - name: Build Project
#       run: npm run build

